name: 🐈‍⬛ Deploy Vite

on:
  workflow_dispatch:
  push:
    branches:
      - main # 🔄 Mỗi lần push lên main, workflow sẽ chạy

jobs:
  build:
    name: Build project 🔨
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v3

      - name: 📦 Cài Node.js
        uses: actions/setup-node@v3

      - name: 🛠️ Tải dependencies
        uses: bahmutov/npm-install@v1

      - name: 🏗️ Build dự án
        run: npm run build

      - name: 📤 Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy lên GitHub pages 🚀
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 📥 Tải build artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: 🌐 Deploy lên nhánh gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
