name: Update README with deploy.yml

on:
  workflow_dispatch: # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest deploy.yml
        run: |
          curl -sL "https://raw.githubusercontent.com/ThinhPhoenix/github-pages/refs/heads/main/deploy.yml" -o deploy.yml

      - name: Update README.md
        run: |
          # Extract deploy.yml content
          DEPLOY_CONTENT=$(awk '{print "    " $0}' deploy.yml)

          # Replace ```yml ... ``` in README.md
          awk -v content="$DEPLOY_CONTENT" '
            BEGIN { inside_block=0 }
            /^```yml$/ { print; inside_block=1; print content; next }
            /^```$/ && inside_block { inside_block=0; next }
            !inside_block { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update deploy.yml in README"
            git push
          fi
